export const IS_LOADING_MOVIES = 'IS_LOADING_MOVIES';
export const FETCH_MOVIES_RESULTS_SUCCESS = 'FETCH_MOVIES_RESULTS_SUCCESS';
export const FETCH_MOVIES_RESULTS_FAILURE = 'FETCH_MOVIES_RESULTS_FAILURE';